
-- sudo su postgres
-- createuser marcianos_user
-- createdb marcianos_db --owner marcianos_user
-- psql
-- alter user marcianos_user with password '12345';
-- \q
-- psql marcianos_db


DROP TABLE IF EXISTS records CASCADE;
CREATE TABLE records (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"time" integer
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO marcianos_user;

REVOKE ALL ON records FROM public;
GRANT ALL ON records TO marcianos_user;